// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/ai" | "/admin/checklist" | "/admin/docs" | "/admin/economy" | "/admin/gate" | "/admin/levels" | "/admin/play/[levelId]" | "/admin/skins" | "/chapters" | "/how-to-play" | "/hunt/[levelId]" | "/levels/[chapterId]" | "/not-found-admin" | "/play/[levelId]" | "/privacy" | "/quests" | "/settings" | "/skins"
type AppRouteHandlerRoutes = "/api/admin/unlock"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/quests" | "/settings"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/ai": {}
  "/admin/checklist": {}
  "/admin/docs": {}
  "/admin/economy": {}
  "/admin/gate": {}
  "/admin/levels": {}
  "/admin/play/[levelId]": { "levelId": string; }
  "/admin/skins": {}
  "/api/admin/unlock": {}
  "/chapters": {}
  "/how-to-play": {}
  "/hunt/[levelId]": { "levelId": string; }
  "/levels/[chapterId]": { "chapterId": string; }
  "/not-found-admin": {}
  "/play/[levelId]": { "levelId": string; }
  "/privacy": {}
  "/quests": {}
  "/settings": {}
  "/skins": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/quests": never
  "/settings": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
